apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from apps.home import blueprint
from flask import render_template, request, Response, jsonify
from flask_login import login_required, current_user
from jinja2 import TemplateNotFound

# ---------------------------------------
import cv2
import datetime, time
import os, sys
import numpy as np
from threading import Thread
from .apply_mask import applyMask
from os import listdir
from os.path import isfile, join
from itertools import cycle

global capture, rec_frame, listmask, len_list, mask, switch, face, rec, out
capture = 0
face = 0
switch = 1
rec = 0
listmask = [f for f in listdir("./mask") if isfile(join("./mask", f))]
index_list = 0
mask = ""

# model load
modelFile = r"models\dnn\res10_300x300_ssd_iter_140000.caffemodel"
configFile = r"models\dnn\deploy.prototxt.txt"
net = cv2.dnn.readNetFromCaffe(configFile, modelFile)
# landmarks load
facemark = cv2.face.createFacemarkLBF()
facemark_path = r"models\lbf\lbfmodel.yaml"
facemark.loadModel(facemark_path)

camera = cv2.VideoCapture(0)
# camera = cv2.VideoCapture(r"D:\Project\AIP\data\Mark Ronson  Uptown Funk Official Video ft Bruno Mars_480p.mp4")

folder_path = ""
rec_frame = None


def record(out):
    global rec_frame
    while rec:
        time.sleep(0.05)
        out.write(rec_frame)


def detect_face(frame, mask):
    global net
    (h, w) = frame.shape[:2]
    blob = cv2.dnn.blobFromImage(
        cv2.resize(frame, (300, 300)), 1.0, (300, 300), (104.0, 177.0, 123.0)
    )
    net.setInput(blob)
    detections = net.forward()

    ########## detect 1 face
    # confidence = detections[0, 0, 0, 2]

    # if confidence < 0.5:
    #         return frame
    # box = detections[0, 0, 0, 3:7] * np.array([w, h, w, h])

    # (startX, startY, endX, endY) = box.astype("int")
    # (x, y, x1, y1) = box.astype("int")

    # cv2.rectangle(frame, (x, y), (x1, y1), (0, 0, 255), 2)

    ########## detect multiple faces
    face_mark = []
    for i in range(detections.shape[2]):
        confidence = detections[0, 0, i, 2]
        if confidence > 0.90:
            box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
            (x, y, x1, y1) = box.astype("int")

            face_mark.append([x, y, x1 - x, y1 - y])

    landmarks = None
    if len(face_mark) > 0:
        try:
            face_mark = np.array(face_mark)
            status, landmarks = facemark.fit(frame, face_mark)

            nose_image = cv2.imread(
                os.path.sep.join(
                    [
                        "./mask",
                        mask,
                    ]
                )
            )

            frame = applyMask(frame, landmarks, nose_image)
        except:
            pass

    return frame


def gen_frames():  # generate frame by frame from camera
    global out, capture, rec_frame, mask
    while True:
        success, frame = camera.read()
        if success:
            mask = listmask[index_list]
            if mask:
                frame = detect_face(frame, mask)
            if capture:
                capture = 0
                now = datetime.datetime.now()
                p = os.path.sep.join(
                    [
                        folder_path + "/images",
                        "shot_{}.png".format(
                            str(now).replace(":", "").replace(" ", "")
                        ),
                    ]
                )
                print(p)
                cv2.imwrite(p, cv2.flip(frame, 1))

            if rec:
                rec_frame = frame
                frame = cv2.putText(
                    cv2.flip(frame, 1),
                    "Recording...",
                    (0, 25),
                    cv2.FONT_HERSHEY_DUPLEX,
                    1,
                    (0, 255, 0),
                    2,
                )
                frame = cv2.flip(frame, 1)

            try:
                ret, buffer = cv2.imencode(".jpg", cv2.flip(frame, 1))

                frame = buffer.tobytes()
                yield (
                    b"--frame\r\n" b"Content-Type: image/jpeg\r\n\r\n" + frame + b"\r\n"
                )
            except Exception as e:
                pass

        else:
            pass


@blueprint.route("/video_feed")
def video_feed():
    return Response(gen_frames(), mimetype="multipart/x-mixed-replace; boundary=frame")


@blueprint.route("/requests", methods=["POST", "GET"])
def tasks():
    global switch, camera, folder_path
    folder_path = current_user.folder_path

    if request.method == "POST":
        if request.form.get("click") == "Capture":
            global capture
            capture = 1
        elif request.form.get("face") == "Change":
            global index_list
            if index_list == len(listmask) - 1:
                index_list = 0
            else:
                index_list = index_list + 1
        elif request.form.get("stop") == "Stop/Start":

            if switch == 1:
                switch = 0
                camera.release()
                cv2.destroyAllWindows()

            else:
                camera = cv2.VideoCapture(0)
                switch = 1
        elif request.form.get("rec") == "Start/Stop Recording":
            global rec, out
            rec = not rec
            if rec:
                now = datetime.datetime.now()
                fourcc = cv2.VideoWriter_fourcc(*"XVID")
                p = os.path.sep.join(
                    [
                        folder_path + "/videos",
                        "vid_{}.avi".format(str(now).replace(":", "")),
                    ]
                )
                out = cv2.VideoWriter(p, fourcc, 20.0, (640, 480))
                # Start new thread for recording the video
                thread = Thread(
                    target=record,
                    args=[
                        out,
                    ],
                )
                thread.start()
            elif rec == False:
                out.release()

    elif request.method == "GET":
        return render_template("home/index.html")
    return render_template("home/index.html")


@blueprint.route("/index", methods=["GET", "POST"])
@login_required
def index():
    global folder_path
    folder_path = current_user.folder_path
    return render_template("home/index.html", segment="index")


@blueprint.route("/table")
@login_required
def table():
    global folder_path
    folder_path = current_user.folder_path
    video_path = folder_path + "/videos"
    image_path = folder_path + "/images"
    video_list = image_list = []
    video_list = [
        "/shots/username_" + current_user.username + "/videos/" + f
        for f in listdir(video_path)
        if isfile(join(video_path, f))
    ]
    image_list = [
        "/shots/username_" + current_user.username + "/images/" + f
        for f in listdir(image_path)
        if isfile(join(image_path, f))
    ]

    return render_template(
        "/home/table-basic.html",
        segment="table",
        video_list=video_list,
        video_len=len(video_list),
        image_list=image_list,
        image_len=len(image_list),
    )


@blueprint.route("/<template>")
@login_required
def route_template(template):

    try:

        if not template.endswith(".html"):
            template += ".html"

        # Detect the current page
        segment = get_segment(request)

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment)

    except TemplateNotFound:
        return render_template("home/page-404.html"), 404

    except:
        return render_template("home/page-500.html"), 500


# Helper - Extract current page name from request
def get_segment(request):

    try:

        segment = request.path.split("/")[-1]

        if segment == "":
            segment = "index"

        return segment

    except:
        return None

apps/templates/home/index.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

<!-- chartist CSS -->
<link href="{{ config.ASSETS_ROOT }}/plugins/chartist-js/dist/chartist.min.css" rel="stylesheet">
<link href="{{ config.ASSETS_ROOT }}/plugins/chartist-js/dist/chartist-init.css" rel="stylesheet">
<link href="{{ config.ASSETS_ROOT }}/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css"
    rel="stylesheet">
<!--This page css - Morris CSS -->
<link href="{{ config.ASSETS_ROOT }}/plugins/c3-master/c3.min.css" rel="stylesheet">

{% endblock stylesheets %}

{% block content %}

<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="page-breadcrumb">
    <div class="row align-items-center">
        <div class="col-md-6 col-8 align-self-center">
            <h3 class="page-title mb-0 p-0">Dashboard</h3>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- <div class="col-md-6 col-4 align-self-center">
            <div class="text-end upgrade-btn">
                <a href="https://appseed.us/support/" class="btn btn-danger d-none d-md-inline-block text-white"
                    target="_blank">
                    Support
                </a>
            </div>
        </div> -->
    </div>
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Container fluid  -->
<!-- ============================================================== -->
<div class="container-fluid">

    <h1>Streaming Video</h1>
    <div class="row">
        <div class="col-8">
            <img id="video" src="{{ url_for('home_blueprint.video_feed') }}" width="100%" height="100%">
        </div>
        <div class="col-4">
            <form method="post" action="{{ url_for('home_blueprint.tasks') }}">
                <div class="col-sm-12">
                    <button class="btn btn-success text-white" type="submit" name="stop" value="Stop/Start">Stop/Start
                        Video</button><br><br>
                    <button class="btn btn-success text-white" type="submit" name="face" value="Change">Change
                        filter</button><br><br>
                    <button class="btn btn-success text-white" type="submit" name="click"
                        value="Capture">Capture</button><br><br>
                    <button class="btn btn-success text-white" type="submit" name="rec"
                        value="Start/Stop Recording">Start/Stop
                        Recording</button>
                </div>
            </form>
        </div>
    </div>


</div>
<!-- ============================================================== -->
<!-- End Container fluid  -->
<!-- ============================================================== -->

{% endblock content %}

{% block javascripts %}

<!-- ============================================================== -->
<!-- This page plugins -->
<!-- ============================================================== -->
<!-- chartist chart -->
<script src="{{ config.ASSETS_ROOT }}/plugins/chartist-js/dist/chartist.min.js"></script>
<script
    src="{{ config.ASSETS_ROOT }}/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.min.js"></script>
<!--c3 JavaScript -->
<script src="{{ config.ASSETS_ROOT }}/plugins/d3/d3.min.js"></script>
<script src="{{ config.ASSETS_ROOT }}/plugins/c3-master/c3.min.js"></script>
<!--Custom JavaScript -->
<script src="{{ config.ASSETS_ROOT }}/js/pages/dashboards/dashboard1.js"></script>

{% endblock javascripts %}

apps/templates/home/page-403.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 403 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- ============================================================== -->
    <!-- Login box.scss -->
    <!-- ============================================================== -->
    <div class="error-box">
        <div class="error-body text-center">
            <h1 class="error-title">403</h1>
            <h3 class="text-uppercase error-subtitle">
                Access denied.
            </h3>
            <p class="text-muted mb-4 mt-4">
                Please authenticate or contact support.    
            </p>
            <a href="/" class="btn btn-info btn-rounded waves-effect waves-light mb-4 text-white">Back to home</a>
        </div>
        <footer class="footer text-center w-100">
            &copy; WrapPixel - Coded by AppSeed.
        </footer>
    </div>

{% endblock content %}

{% block javascripts %}

    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
        $(".preloader").fadeOut();
    </script>

{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- ============================================================== -->
    <!-- Login box.scss -->
    <!-- ============================================================== -->
    <div class="error-box">
        <div class="error-body text-center">
            <h1 class="error-title">404</h1>
            <h3 class="text-uppercase error-subtitle">PAGE NOT FOUND !</h3>
            <p class="text-muted mb-4 mt-4">YOU SEEM TO BE TRYING TO FIND HIS WAY HOME</p>
            <a href="/" class="btn btn-info btn-rounded waves-effect waves-light mb-4 text-white">Back to home</a>
        </div>
        <footer class="footer text-center w-100">
            &copy; WrapPixel - Coded by AppSeed.
        </footer>
    </div>

{% endblock content %}

{% block javascripts %}

    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
        $(".preloader").fadeOut();
    </script>

{% endblock javascripts %}

apps/templates/home/page-500.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 500 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- ============================================================== -->
    <!-- Login box.scss -->
    <!-- ============================================================== -->
    <div class="error-box">
        <div class="error-body text-center">
            <h1 class="error-title">500</h1>
            <h3 class="text-uppercase error-subtitle">
                SERVER ERROR
            </h3>
            <p class="text-muted mb-4 mt-4">
                Please retry to access the page in a few minutes.   
            </p>
            <a href="/" class="btn btn-info btn-rounded waves-effect waves-light mb-4 text-white">Back to home</a>
        </div>
        <footer class="footer text-center w-100">
            &copy; WrapPixel - Coded by AppSeed.
        </footer>
    </div>

{% endblock content %}

{% block javascripts %}

    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
        $(".preloader").fadeOut();
    </script>

{% endblock javascripts %}

apps/templates/home/page-blank.html
{% extends "layouts/base.html" %}

{% block title %} Page Blank {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row align-items-center">
                <div class="col-md-6 col-8 align-self-center">
                    <h3 class="page-title mb-0 p-0">Blank Page</h3>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Blank Page</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="col-md-6 col-4 align-self-center">
                    <div class="text-end upgrade-btn">
                        <a href="https://appseed.us/support/"
                            class="btn btn-danger d-none d-md-inline-block text-white" target="_blank">
                            Support        
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            This is some text within a card block.
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Right sidebar -->
            <!-- ============================================================== -->
            <!-- .right-sidebar -->
            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->

{% endblock content %}

{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-profile.html
{% extends "layouts/base.html" %}

{% block title %} User Profile {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row align-items-center">
                <div class="col-md-6 col-8 align-self-center">
                    <h3 class="page-title mb-0 p-0">Profile</h3>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Profile</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="col-md-6 col-4 align-self-center">
                    <div class="text-end upgrade-btn">
                        <a href="https://appseed.us/support/"
                            class="btn btn-danger d-none d-md-inline-block text-white" target="_blank">
                            Support        
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <!-- Row -->
            <div class="row">
                <!-- Column -->
                <div class="col-lg-4 col-xlg-3 col-md-5">
                    <div class="card">
                        <div class="card-body profile-card">
                            <center class="mt-4"> 
                                <img src="{{ config.ASSETS_ROOT }}/images/users/5.jpg"
                                    class="rounded-circle" width="150" />
                                <h4 class="card-title mt-2">Hanna Gover</h4>
                                <h6 class="card-subtitle">Accoubts Manager Amix corp</h6>
                                <div class="row text-center justify-content-center">
                                    <div class="col-4">
                                        <a href="javascript:void(0)" class="link">
                                            <i class="icon-people" aria-hidden="true"></i>
                                            <span class="value-digit">254</span>
                                        </a></div>
                                    <div class="col-4">
                                        <a href="javascript:void(0)" class="link">
                                            <i class="icon-picture" aria-hidden="true"></i>
                                            <span class="value-digit">54</span>
                                        </a></div>
                                </div>
                            </center>
                        </div>
                    </div>
                </div>
                <!-- Column -->
                <!-- Column -->
                <div class="col-lg-8 col-xlg-9 col-md-7">
                    <div class="card">
                        <div class="card-body">
                            <form class="form-horizontal form-material mx-2">
                                <div class="form-group">
                                    <label class="col-md-12 mb-0">Full Name</label>
                                    <div class="col-md-12">
                                        <input type="text" placeholder="Johnathan Doe"
                                            class="form-control ps-0 form-control-line">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="example-email" class="col-md-12">Email</label>
                                    <div class="col-md-12">
                                        <input type="email" placeholder="johnathan@admin.com"
                                            class="form-control ps-0 form-control-line" name="example-email"
                                            id="example-email">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12 mb-0">Password</label>
                                    <div class="col-md-12">
                                        <input type="password" value="password"
                                            class="form-control ps-0 form-control-line">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12 mb-0">Phone No</label>
                                    <div class="col-md-12">
                                        <input type="text" placeholder="123 456 7890"
                                            class="form-control ps-0 form-control-line">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12 mb-0">Message</label>
                                    <div class="col-md-12">
                                        <textarea rows="5" class="form-control ps-0 form-control-line"></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-12">Select Country</label>
                                    <div class="col-sm-12 border-bottom">
                                        <select class="form-select shadow-none ps-0 border-0 form-control-line">
                                            <option>London</option>
                                            <option>India</option>
                                            <option>Usa</option>
                                            <option>Canada</option>
                                            <option>Thailand</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-12 d-flex">
                                        <button class="btn btn-success mx-auto mx-md-0 text-white">Update
                                            Profile</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- Column -->
            </div>
            <!-- Row -->
            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Right sidebar -->
            <!-- ============================================================== -->
            <!-- .right-sidebar -->
            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->

{% endblock content %}

{% block javascripts %}{% endblock javascripts %}